<?php

return [
    [
        'aliases' => ['la pola planta 2', 'la pola 2'],
        'display_name' => 'Tanque 2',
        'altura_maxima' => 4.04,
        'area_m2' => 220,
        'altura_rebose' => null,
        'volumen_m3' => null,
        'cota_rebose' => null,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['la pola planta 1', 'la pola 1', 'la pola'],
        'display_name' => 'Tanque 1',
        'altura_maxima' => 4.24,
        'area_m2' => 220,
        'altura_rebose' => null,
        'volumen_m3' => null,
        'cota_rebose' => null,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    // Ajuste provisional del 2026-08-20: este valor de altura_rebose se corrigió por discrepancia con IBAL.
    // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
    // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
    [
        'aliases' => ['interlaken'],
        'display_name' => 'Interlaken',
        'altura_maxima' => 5.0,
        'area_m2' => 161.759,
        'altura_rebose' => 4.4796296296,
        'volumen_m3' => 500,
        'cota_rebose' => 1255.67,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['1 ambala', 'ambala 1'],
        'display_name' => 'Ambala 1',
        'altura_maxima' => 5.12,
        'area_m2' => 730.976,
        'altura_rebose' => 6.4252941176,
        'volumen_m3' => 5000,
        'cota_rebose' => 1170.14,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['2 ambala', 'ambala 2'],
        'display_name' => 'Ambala 2',
        'altura_maxima' => 5.2,
        'area_m2' => 730.976,
        'altura_rebose' => 6.44569,
        'volumen_m3' => 5000,
        'cota_rebose' => 1170.14,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['alsacia'],
        'display_name' => 'Alsacia',
        'altura_maxima' => 4.69,
        'area_m2' => 337.067,
        'altura_rebose' => 2.4655263157894737,
        'volumen_m3' => 1000,
        'cota_rebose' => 1057.42,
        'alarma_llenado' => 2.30,
        'alarma_vacio' => 0.50,
    ],
    // Ajuste provisional del 2026-08-20: este valor de altura_rebose se corrigió por discrepancia con IBAL.
    // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
    // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
    [
        'aliases' => ['calucaima', 'caluc aima'],
        'display_name' => 'Calucaima',
        'altura_maxima' => 5.0,
        'area_m2' => 220,
        'altura_rebose' => 5.0243902439,
        'volumen_m3' => null,
        'cota_rebose' => null,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['ciudad'],
        'display_name' => 'Ciudad',
        'altura_maxima' => 5.0,
        'area_m2' => 787.045,
        'altura_rebose' => 3.81,
        'volumen_m3' => 3000,
        'cota_rebose' => 1310.97,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['la aurora', 'aurora', 'la aurora antiguo', 'la aurora (antiguo)', 'la aurora nuevo', 'la aurora (nuevo)', 'la aurora nuevo'],
        'display_name' => 'La Aurora',
        'altura_maxima' => 5.0,
        'area_m2' => 449.4054,
        'altura_rebose' => 3.9884444444444446,
        'volumen_m3' => 1800,
        'cota_rebose' => 1359.70,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['belen', 'belen 1', 'belen 2', 'belen norte', 'belen sur', 'belén'],
        'display_name' => 'Belén',
        'altura_maxima' => 5.0,
        'area_m2' => 787.045,
        'altura_rebose' => 3.81,
        'volumen_m3' => 3000,
        'cota_rebose' => 1310.97,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    // Ajuste provisional del 2026-08-20: este valor de altura_rebose se corrigió por discrepancia con IBAL.
    // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
    // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
    [
        'aliases' => ['la quince', 'la 15', 'calle 15'],
        'display_name' => 'La Quince',
        'altura_maxima' => 5.0,
        'area_m2' => 461.2055,
        'altura_rebose' => 8.4403921569,
        'volumen_m3' => 4000,
        'cota_rebose' => 1264.30,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    // Ajuste provisional del 2026-08-20: este valor de altura_rebose se corrigió por discrepancia con IBAL.
    // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
    // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
    [
        'aliases' => ['la 29', 'calle 29', 'tanque 29'],
        'display_name' => 'Tanque 29',
        'altura_maxima' => 5.0,
        'area_m2' => 1476,
        'altura_rebose' => 6.6551724138,
        'volumen_m3' => 6100,
        'cota_rebose' => 1212.79,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    // Ajuste provisional del 2026-08-20: este valor de altura_rebose se corrigió por discrepancia con IBAL.
    // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
    // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
    [
        'aliases' => ['la 30', 'calle 30', 'tanque 30'],
        'display_name' => 'Tanque 30',
        'altura_maxima' => 5.0,
        'area_m2' => 299.7672,
        'altura_rebose' => 7.0185185185,
        'volumen_m3' => 6100,
        'cota_rebose' => 1213.94,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['1 p pintada', 'p pintada 1', 'piedra pintada 1'],
        'display_name' => 'Pintada 1',
        'altura_maxima' => 5.0,
        'area_m2' => 1079.411,
        'altura_rebose' => 4.2035,
        'volumen_m3' => 4000,
        'cota_rebose' => 1171.94,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['2 p pintada', 'p pintada 2', 'piedra pintada 2'],
        'display_name' => 'Pintada 2',
        'altura_maxima' => 5.0,
        'area_m2' => 275.301,
        'altura_rebose' => 4.746081081081081,
        'volumen_m3' => 1000,
        'cota_rebose' => 1172.19,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    // Ajuste provisional del 2026-08-20: este valor de altura_rebose se corrigió por discrepancia con IBAL.
    // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
    // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
    [
        'aliases' => ['miramar'],
        'display_name' => 'Miramar',
        'altura_maxima' => 5.0,
        'area_m2' => 220,
        'altura_rebose' => 7.46875,
        'volumen_m3' => null,
        'cota_rebose' => null,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['zona industrial', 'de zona industrial'],
        'display_name' => 'Zona Industrial',
        'altura_maxima' => 5.0,
        'area_m2' => 660.93,
        'altura_rebose' => 16.77777777777778,
        'volumen_m3' => 10627.49,
        'cota_rebose' => 1197.20,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['1 cerro'],
        'display_name' => 'Cerro 1',
        'altura_maxima' => 5.0,
        'area_m2' => 220,
        'altura_rebose' => null,
        'volumen_m3' => null,
        'cota_rebose' => null,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['1 cerro gordo', 'cerro gordo 1'],
        'display_name' => 'Cerro Gordo 1',
        'altura_maxima' => 5.0,
        'area_m2' => 271.44,
        'altura_rebose' => 3.985,
        'volumen_m3' => 1000,
        'cota_rebose' => 1253.41,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['2 cerro gordo', 'cerro gordo 2'],
        'display_name' => 'Cerro Gordo 2',
        'altura_maxima' => 5.0,
        'area_m2' => 271.44,
        'altura_rebose' => 4.015769230769231,
        'volumen_m3' => 1000,
        'cota_rebose' => 1253.41,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['mirolindo'],
        'display_name' => 'Mirolindo',
        'altura_maxima' => 5.0,
        'area_m2' => 351,
        'altura_rebose' => 2.7884615384615386,
        'volumen_m3' => 10000,
        'cota_rebose' => 1102.32,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['1 picalena', 'picalena 1', 'picaleña 1'],
        'display_name' => 'Picaleña 1',
        'altura_maxima' => 5.0,
        'area_m2' => 114,
        'altura_rebose' => 2.7781609195402297,
        'volumen_m3' => 400,
        'cota_rebose' => 88.49,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['2 picalena', 'picalena 2', 'picaleña 2'],
        'display_name' => 'Picaleña 2',
        'altura_maxima' => 5.0,
        'area_m2' => 196.185,
        'altura_rebose' => 3.7868055555555556,
        'volumen_m3' => 1000,
        'cota_rebose' => 88.36,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['piedra pintada 1'],
        'display_name' => 'Piedra Pintada 1',
        'altura_maxima' => 5.0,
        'area_m2' => 1079.411,
        'altura_rebose' => 4.2035,
        'volumen_m3' => null,
        'cota_rebose' => null,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['piedra pintada 2'],
        'display_name' => 'Piedra Pintada 2',
        'altura_maxima' => 5.0,
        'area_m2' => 275.301,
        'altura_rebose' => 4.746081081081081,
        'volumen_m3' => null,
        'cota_rebose' => null,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['sur'],
        'display_name' => 'Sur',
        'altura_maxima' => 5.0,
        'area_m2' => 286.491,
        'altura_rebose' => 10.56,
        'volumen_m3' => 2036.95,
        'cota_rebose' => 1291.58,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
    [
        'aliases' => ['cerro gordo 3', 'cerro gordo 3', '3 cerro gordo'],
        'display_name' => 'Cerro Gordo 3',
        'altura_maxima' => 5.0,
        'area_m2' => 29.16,
        'altura_rebose' => 1.75,
        'volumen_m3' => 329.16,
        'cota_rebose' => 1281.10,
        'alarma_llenado' => null,
        'alarma_vacio' => null,
    ],
];
