const TANQUES_CONFIG = [
  {
    aliases: ["la pola planta 2", "la pola 2", "la 2", "tanque la 2"],
    display_name: "Tanque 2",
    area: 220,
    altura_total: 4.04,
    altura_rebose: null,
    volumen: null,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["la pola planta 1", "la pola 1", "la pola"],
    display_name: "Tanque 1",
    area: 220,
    altura_total: 4.24,
    altura_rebose: null,
    volumen: null,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque picaleña 1", "tanque picalena 1", "picaleña 1", "picalena 1"],
    display_name: "Picaleña 1",
    area: 114,
    altura_total: 4.25,
    altura_rebose: 2.7781609195402297,
    altura_rebose_calibrada: 2.7781609195402297,
    volumen: 400,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque picaleña 2", "tanque picalena 2", "picaleña 2", "picalena 2"],
    display_name: "Picaleña 2",
    area: 196.185,
    altura_total: 3.15,
    altura_rebose: 3.7868055555555556,
    altura_rebose_calibrada: 3.7868055555555556,
    volumen: 1000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  // Ajuste provisional del 2026-08-20: se corrigió esta altura_rebose_calibrada por discrepancia con IBAL.
  // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
  // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
  {
    aliases: ["tanque la 15", "la 15", "la quince", "tanque 15", "calle 15"],
    display_name: "Tanque La 15",
    area: 461.2055,
    altura_total: 8.32,
    altura_rebose: 7.77,
    altura_rebose_calibrada: 8.4403921569,
    volumen: 4000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  // Ajuste provisional del 2026-08-20: se corrigió esta altura_rebose_calibrada por discrepancia con IBAL.
  // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
  // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
  {
    aliases: ["tanque interlaken", "interlaken"],
    display_name: "Interlaken",
    area: 161.759,
    altura_total: 4.65,
    altura_rebose: 4.35,
    altura_rebose_calibrada: 4.4796296296,
    volumen: 500,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque mirolindo", "mirolindo"],
    display_name: "Mirolindo",
    area: 351,
    altura_total: 3.15,
    altura_rebose: 2.7884615384615386,
    altura_rebose_calibrada: 2.7884615384615386,
    volumen: 10000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque ambala 1", "ambala 1"],
    display_name: "Ambala 1",
    area: 730.976,
    altura_total: 7,
    altura_rebose: 6.4252941176,
    altura_rebose_calibrada: 6.4252941176,
    volumen: 5000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque ambala 2", "ambala 2"],
    display_name: "Ambala 2",
    area: 730.976,
    altura_total: 7,
    altura_rebose: 6.44569,
    altura_rebose_calibrada: 6.44569,
    volumen: 5000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque alsacia", "alsacia", "la alsacia", "alsacia salado"],
    display_name: "Alsacia",
    area: 337.067,
    altura_total: 2.97,
    altura_rebose: 2.4655263157894737,
    altura_rebose_calibrada: 2.4655263157894737,
    volumen: 1000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque belen", "belen", "belén"],
    display_name: "Belén",
    area: 787.045,
    altura_total: 4.2,
    altura_rebose: 3.81,
    altura_rebose_calibrada: 3.81,
    volumen: 3000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  // Ajuste provisional del 2026-08-20: se corrigió esta altura_rebose_calibrada por discrepancia con IBAL.
  // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
  // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
  {
    aliases: ["calucaima", "calucaima", "caluc aima", "tanque calucaima", "tanque caluc aima"],
    display_name: "Calucaima",
    area: null,
    altura_total: null,
    altura_rebose: null,
    altura_rebose_calibrada: 5.0243902439,
    volumen: null,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  // Ajuste provisional del 2026-08-20: se corrigió esta altura_rebose_calibrada por discrepancia con IBAL.
  // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
  // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
  {
    aliases: ["miramar", "tanque miramar"],
    display_name: "Miramar",
    area: null,
    altura_total: null,
    altura_rebose: null,
    altura_rebose_calibrada: 7.46875,
    volumen: null,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["villamarin", "tanque villamarin"],
    display_name: "Villamarin",
    area: null,
    altura_total: null,
    altura_rebose: null,
    volumen: null,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["2000", "tanque 2000"],
    display_name: "2000",
    area: null,
    altura_total: null,
    altura_rebose: null,
    volumen: null,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  // Ajuste provisional del 2026-08-20: se corrigió esta altura_rebose_calibrada por discrepancia con IBAL.
  // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
  // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
  {
    aliases: ["tanque la 30", "la 30", "calle 30", "tanque 30"],
    display_name: "Tanque La 30",
    area: 299.7672,
    altura_total: 7,
    altura_rebose: 7.14,
    altura_rebose_calibrada: 7.0185185185,
    volumen: 6100,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  // Ajuste provisional del 2026-08-20: se corrigió esta altura_rebose_calibrada por discrepancia con IBAL.
  // Se calculó con un solo punto de referencia (nivel_sensor + % IBAL en ese instante), no es medición física en campo.
  // Debe revisarse/reconfirmarse en unos días comparando de nuevo contra IBAL para verificar si el % se mantiene alineado o vuelve a desviarse.
  {
    aliases: ["tanque la 29", "la 29", "calle 29", "tanque 29"],
    display_name: "Tanque La 29",
    area: 1476,
    altura_total: 3.96,
    altura_rebose: 3.01,
    altura_rebose_calibrada: 6.6551724138,
    volumen: 6100,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque cerrogordo 1", "cerrogordo 1", "cerro gordo 1"],
    display_name: "Cerro Gordo 1",
    area: 271.44,
    altura_total: 4.52,
    altura_rebose: 3.985,
    altura_rebose_calibrada: 3.985,
    volumen: 1000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque piedra pintada 1", "piedra pintada 1", "piedrapintada 1"],
    display_name: "Piedra Pintada 1",
    area: 1079.411,
    altura_total: 5,
    altura_rebose: 4.2035,
    altura_rebose_calibrada: 4.2035,
    volumen: 4000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque ciudad", "ciudad"],
    display_name: "Ciudad",
    area: 787.045,
    altura_total: 4.2,
    altura_rebose: 3.81,
    altura_rebose_calibrada: 3.81,
    volumen: 3000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque cerrogordo 2", "cerrogordo 2", "cerro gordo 2"],
    display_name: "Cerro Gordo 2",
    area: 271.44,
    altura_total: 4.52,
    altura_rebose: 4.015769230769231,
    altura_rebose_calibrada: 4.015769230769231,
    volumen: 1000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque piedra pintada 2", "piedra pintada 2", "piedrapintada 2"],
    display_name: "Piedra Pintada 2",
    area: 275.301,
    altura_total: 4,
    altura_rebose: 4.746081081081081,
    altura_rebose_calibrada: 4.746081081081081,
    volumen: 1000,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque cerrogordo 3", "cerrogordo 3", "cerro gordo 3"],
    display_name: "Cerro Gordo 3",
    area: 29.16,
    altura_total: 2,
    altura_rebose: 1.75,
    volumen: 29.16,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque la aurora nuevo", "la aurora nuevo", "la aurora (nuevo)", "aurora", "la aurora", "tanque la aurora antiguo", "la aurora antiguo", "la aurora (antiguo)"],
    display_name: "La Aurora",
    area: 449.4054,
    altura_total: 3.2,
    altura_rebose: 3.9884444444444446,
    altura_rebose_calibrada: 3.9884444444444446,
    volumen: 1800,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque zona industrial", "zona industrial"],
    display_name: "Zona Industrial",
    area: 660.93,
    altura_total: 16.29,
    altura_rebose: 16.77777777777778,
    altura_rebose_calibrada: 16.77777777777778,
    volumen: 10627.49,
    largo: null,
    ancho: null,
    compartimientos: null,
  },
  {
    aliases: ["tanque sur", "sur", "tanque sur"],
    display_name: "Sur",
    area: 286.491,
    altura_total: 7.11,
    altura_rebose: 6.56,
    largo: null,
    ancho: null,    
    compartimientos: null,
  },
];

export { TANQUES_CONFIG };
